// Somali STEM Courses Data - Optimized for SEO
import type { Category } from "@/types/lms";

export const mockCategories: Category[] = [
  {
    id: "1",
    title: "Xisaab Soomaali (Somali Math)",
    description:
      "Barashada xisaabta ee Soomaalida - algebra, geometry, calculus iyo xisaabta aasaasiga.",
    image: "./images/math-icon.svg",
    inProgress: true,
    courses: [
      {
        id: 1,
        title: "Xisaabta Aasaasiga - Somali Basic Math",
        slug: "xisaabta-aasaasiga-somali-basic-math",
        thumbnail: "./images/courses/math/solving-equations.svg",
        is_new: true,
        description:
          "Barashada xisaabta aasaasiga ee Soomaalida - isle'egyada, tirooyinka, iyo xisaabta guud.",
        progress: 15,
        level: "beginner",
        category_id: "somali-math",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 12,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 2,
        title: "Algebra Soomaali - Somali Algebra",
        slug: "algebra-soomaali-somali-algebra",
        thumbnail: "./images/courses/math/functions.svg",
        is_new: true,
        description:
          "Barashada algebra ee Soomaalida - functions, equations, iyo algebraic expressions.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-algebra",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 15,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 3,
        title: "Geometry Soomaali - Somali Geometry",
        slug: "geometry-soomaali-somali-geometry",
        thumbnail: "./images/courses/math/geometry.svg",
        is_new: true,
        description:
          "Barashada geometry ee Soomaalida - shapes, angles, areas, iyo volumes.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-geometry",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 18,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 4,
        title: "Xisaabta Heerka Sare - Advanced Somali Math",
        slug: "xisaabta-heerka-sare-advanced-somali-math",
        thumbnail: "./images/courses/math/real-world-algebra.svg",
        is_new: false,
        description:
          "Barashada xisaabta heerka sare ee Soomaalida - calculus, trigonometry, iyo advanced algebra.",
        progress: 0,
        level: "advanced",
        category_id: "somali-advanced-math",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 20,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
  },
  {
    id: "2",
    title: "Saynis Soomaali (Somali Science)",
    description:
      "Barashada sayniska ee Soomaalida - physics, chemistry, biology iyo sayniska aasaasiga.",
    image: "./images/math-icon.svg",
    inProgress: true,
    courses: [
      {
        id: 5,
        title: "Physics Soomaali - Somali Physics",
        slug: "physics-soomaali-somali-physics",
        thumbnail: "./images/courses/math/visual-algebra.svg",
        is_new: true,
        description:
          "Barashada physics ee Soomaalida - mechanics, electricity, magnetism, iyo modern physics.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-physics",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 16,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 6,
        title: "Chemistry Soomaali - Somali Chemistry",
        slug: "chemistry-soomaali-somali-chemistry",
        thumbnail: "./images/courses/math/solving-equations.svg",
        is_new: true,
        description:
          "Barashada chemistry ee Soomaalida - atoms, molecules, reactions, iyo chemical bonding.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-chemistry",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 14,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 7,
        title: "Biology Soomaali - Somali Biology",
        slug: "biology-soomaali-somali-biology",
        thumbnail: "./images/courses/math/geometry.svg",
        is_new: true,
        description:
          "Barashada biology ee Soomaalida - cells, genetics, evolution, iyo human anatomy.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-biology",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 17,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
  },
  {
    id: "3",
    title: "Technology Soomaali (Somali Technology)",
    description:
      "Barashada technology-ga ee Soomaalida - AI, crypto, programming iyo digital skills.",
    image: "./images/programming-icon.svg",
    inProgress: true,
    courses: [
      {
        id: 8,
        title: "AI Soomaali - Somali Artificial Intelligence",
        slug: "ai-soomaali-somali-artificial-intelligence",
        thumbnail: "./images/courses/programming/ai.svg",
        is_new: true,
        description:
          "Barashada AI ee Soomaalida - machine learning, neural networks, iyo artificial intelligence.",
        progress: 0,
        level: "advanced",
        category_id: "somali-ai",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 22,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 9,
        title: "Crypto Soomaali - Somali Cryptocurrency",
        slug: "crypto-soomaali-somali-cryptocurrency",
        thumbnail: "./images/courses/programming/neural-networks.svg",
        is_new: true,
        description:
          "Barashada cryptocurrency ee Soomaalida - blockchain, Bitcoin, Ethereum, iyo digital finance.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-crypto",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 19,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 10,
        title: "Programming Soomaali - Somali Programming",
        slug: "programming-soomaali-somali-programming",
        thumbnail: "./images/courses/programming/python.svg",
        is_new: true,
        description:
          "Barashada programming ee Soomaalida - Python, JavaScript, web development, iyo software engineering.",
        progress: 0,
        level: "intermediate",
        category_id: "somali-programming",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 25,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 11,
        title: "Data Science Soomaali - Somali Data Science",
        slug: "data-science-soomaali-somali-data-science",
        thumbnail: "./images/courses/programming/cs.svg",
        is_new: true,
        description:
          "Barashada data science ee Soomaalida - data analysis, visualization, iyo machine learning.",
        progress: 0,
        level: "advanced",
        category_id: "somali-data-science",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 20,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
  },
  {
    id: "4",
    title: "STEM Soomaali (Somali STEM)",
    description:
      "Barashada STEM-ka ee Soomaalida - Science, Technology, Engineering, iyo Mathematics.",
    image: "./images/math-icon.svg",
    inProgress: true,
    courses: [
      {
        id: 12,
        title: "STEM Aasaasiga - Somali Basic STEM",
        slug: "stem-aasaasiga-somali-basic-stem",
        thumbnail: "./images/courses/math/functions.svg",
        is_new: true,
        description:
          "Barashada STEM-ka aasaasiga ee Soomaalida - science, technology, engineering, iyo mathematics.",
        progress: 0,
        level: "beginner",
        category_id: "somali-basic-stem",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 30,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 13,
        title: "Engineering Soomaali - Somali Engineering",
        slug: "engineering-soomaali-somali-engineering",
        thumbnail: "./images/courses/programming/3d.svg",
        is_new: true,
        description:
          "Barashada engineering ee Soomaalida - civil, electrical, mechanical, iyo software engineering.",
        progress: 0,
        level: "advanced",
        category_id: "somali-engineering",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 28,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 14,
        title: "Robotics Soomaali - Somali Robotics",
        slug: "robotics-soomaali-somali-robotics",
        thumbnail: "./images/courses/programming/ai.svg",
        is_new: true,
        description:
          "Barashada robotics ee Soomaalida - automation, sensors, programming, iyo robot design.",
        progress: 0,
        level: "advanced",
        category_id: "somali-robotics",
        modules: [],
        author_id: "garaad-team",
        is_published: true,
        module_count: 24,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
  },
];
