import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/courses",
          "/courses/*",
          "/launchpad",
          "/blog",
          "/blog/*",
          "/login",
          "/welcome",
          "/about",
          "/about/*",
          "/privacy",
          "/terms",
          "/webinar",
          "/feedback",
          "/startups",
        ],
        disallow: [
          "/api/",
          "/_next/",
          "/admin",
          "/admin/",
          "/community",
          "/community/",
          "/dashboard",
          "/dashboard/",
          "/profile",
          "/profile/",
          "/orders",
          "/orders/",
          "/verify-email",
          "/verify-email/",
          "/subscribe",
          "/subscribe/",
          "/launchpad/submit",
          "/launchpad/submit/",
          "/launchpad/edit",
          "/launchpad/edit/",
          "/test-*",
          "/payment*",
          "/stripe*",
        ],
      },
    ],
    sitemap: "https://garaad.org/sitemap.xml",
    host: "https://garaad.org",
  };
}
